{% set name = "efficient-apriori" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/efficient_apriori-{{ version }}.tar.gz
  sha256: 5ad8ce4b4f8aee53cc0ef99a804145071bd8bdd652fdfb78cdf2e43831baad6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - efficient_apriori
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: An efficient Python implementation of the Apriori algorithm.
  home: https://github.com/tommyod/Efficient-Apriori
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
